# config server runs in this port, microservices must use this port to connect to 
# config server
server.port=8888
# config server connects to this cloud environment
spring.cloud.config.server.git.uri=https://github.com/Kishor-C/common-config.git
# config server must fetch the configuration file from master branch
spring.cloud.config.server.default-label=master
