spring.application.name=service-discovery-app
server.port=8761
# by default eureka client registers to services discovery 
eureka.client.register-with-eureka=false
# by defalut eueka client reads service discovery registery
eureka.client.fetch-registry=false